export const crimes = [
    { label: "Suspicious Activity", value: "suspicious" },
    { label: "Drug Activity", value: "drug-activity" },
    { label: "Encampment", value: "encampment" },
    { label: "Vandalism", value: "vandalism" },
    { label: "Theft", value: "theft" },
    { label: "Break-in", value: "break-in" },
    { label: "Trespassing", value: "trespassing" },
    { label: "Loitering", value: "loitering" },
    { label: "Noise Complaint", value: "noise" },
    { label: "Vehicle Break-in", value: "vehicle-break-in" },
    { label: "Package Theft", value: "package-theft" },
    { label: "Graffiti", value: "graffiti" },
    { label: "Public Intoxication", value: "intoxication" },
    { label: "Illegal Dumping", value: "dumping" },
    { label: "Harassment", value: "harassment" },
    { label: "Burglary", value: "burglary" },
    { label: "Other", value: "other" },
      ]